CREATE TABLE IF NOT EXISTS omnipath_consent_artifacts (
    consent_id TEXT,
    community_id TEXT,
    knowledge_type TEXT,
    consent_status TEXT,
    consent_scope TEXT,
    tk_labels TEXT,
    bc_labels TEXT,
    signature_rsa4096 TEXT,
    signature_ecdsa TEXT,
    manifest_hash TEXT,
    community_vote_pct REAL,
    revocation_authority TEXT,
    granted_at TEXT,
    expires_at TEXT,
    revoked_at TEXT,
    last_verified_at TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_drug_interactions (
    interaction_id TEXT,
    compound_id TEXT,
    drug_name TEXT,
    drug_class TEXT,
    cyp450_enzyme TEXT,
    interaction_type TEXT,
    inhibition_potency TEXT,
    severity_level TEXT,
    clinical_effect TEXT,
    risk_description TEXT,
    monitoring_required INTEGER,
    monitoring_parameters TEXT,
    dose_adjustment_needed INTEGER,
    adjustment_recommendation TEXT,
    evidence_level TEXT,
    citations TEXT,
    created_at TEXT,
    requires_consent_check INTEGER,
    consent_id TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_compounds (
    compound_id TEXT,
    compound_name TEXT,
    compound_class TEXT,
    kingdom TEXT,
    molecular_formula TEXT,
    molecular_weight REAL,
    smiles TEXT,
    cas_number TEXT,
    primary_mechanisms TEXT,
    therapeutic_targets TEXT,
    bioavailability_oral REAL,
    half_life_hours TEXT,
    ld50_mg_kg TEXT,
    cyp450_interactions TEXT,
    contraindications TEXT,
    botanical_source TEXT,
    traditional_use TEXT,
    is_novel INTEGER,
    patent_protected INTEGER,
    consent_id TEXT,
    traditional_knowledge_flag INTEGER,
    community_attribution TEXT,
    requires_consent_check INTEGER,
    benefit_sharing_required INTEGER,
    available_to_computational_tier INTEGER,
    available_to_tk_tier INTEGER,
    data_source TEXT,
    created_at TEXT,
    updated_at TEXT
);

CREATE TABLE IF NOT EXISTS omnipath_audit_log (
    log_id TEXT,
    event_type TEXT,
    application TEXT,
    event_data TEXT,
    consent_id TEXT,
    policy_id TEXT,
    user_id TEXT,
    result TEXT,
    reason TEXT,
    processing_time_ms TEXT,
    hipaa_deidentified INTEGER,
    timestamp TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_demographic_factors (
    factor_id TEXT,
    demographic_category TEXT,
    demographic_value TEXT,
    cyp450_adjustment REAL,
    dosing_adjustment REAL,
    applicable_compounds TEXT,
    evidence_basis TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_synergy_predictions (
    synergy_id TEXT,
    compound_a_id TEXT,
    compound_b_id TEXT,
    synergy_score REAL,
    synergy_type TEXT,
    mechanism TEXT,
    is_cross_kingdom TEXT,
    kingdom_a TEXT,
    kingdom_b TEXT,
    therapeutic_context TEXT,
    pathway_modulation TEXT,
    confidence_score REAL,
    evidence_basis TEXT,
    optimal_ratio TEXT,
    requires_consent INTEGER,
    consent_verification_status TEXT,
    computation_date TEXT,
    consent_id TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_clinical_studies (
    study_id TEXT,
    study_type TEXT,
    condition TEXT,
    intervention TEXT,
    outcomes TEXT,
    key_findings TEXT,
    citation TEXT,
    pubmed_id TEXT,
    doi TEXT,
    confidence_score REAL,
    sample_size INTEGER,
    study_duration_days TEXT,
    publication_year INTEGER,
    consent_id TEXT,
    traditional_knowledge_source INTEGER,
    community_attribution TEXT,
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_formulations (
    formulation_id TEXT,
    formulation_name TEXT,
    formulation_type TEXT,
    ingredients TEXT,
    target_condition TEXT,
    severity_level TEXT,
    synergy_score REAL,
    confidence_level TEXT,
    predicted_mechanisms TEXT,
    total_dose_mg TEXT,
    doses_per_day TEXT,
    duration_days TEXT,
    interaction_warnings TEXT,
    contraindications TEXT,
    clinical_evidence_level TEXT,
    validation_studies TEXT,
    requires_consent INTEGER,
    consent_ids TEXT,
    benefit_sharing_calculation TEXT,
    community_attributions TEXT,
    tk_enhanced INTEGER,
    non_tk_alternative_available INTEGER,
    pricing_tier_required TEXT,
    created_at TEXT,
    created_by TEXT,
    commercialization_status TEXT
);

CREATE TABLE IF NOT EXISTS neurobotanica_polysaccharides (
    polysaccharide_id TEXT,
    polysaccharide_name TEXT,
    kingdom TEXT,
    polysaccharide_type TEXT,
    glycosidic_linkage TEXT,
    branching_pattern TEXT,
    molecular_weight_kda TEXT,
    degree_of_sulfation TEXT,
    immune_modulation_score TEXT,
    anti_inflammatory_potency TEXT,
    gut_microbiome_effect TEXT,
    neuroprotective_mechanisms TEXT,
    fermentation_rate TEXT,
    scfa_profile TEXT,
    botanical_source TEXT,
    extraction_method TEXT,
    typical_dosage_mg TEXT,
    fucosidase_dependent INTEGER,
    dectin1_responsive INTEGER,
    consent_id TEXT,
    traditional_knowledge_flag INTEGER,
    community_attribution TEXT,
    indigenous_sourcing INTEGER,
    created_at TEXT
);