"""
Adjuvant Model - NeuroBotanica Week 5
Database schema for adjuvant compounds used with cannabinoid formulations.

Supports:
- Receptor priming protocols
- Metabolic enhancers
- Timing optimization
- Drug interaction checking
"""
from sqlalchemy import Column, Integer, String, Float, Boolean, JSON, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .database import Base


class Adjuvant(Base):
    """Adjuvant compound used to enhance cannabinoid effects.
    
    Categories include:
    - Receptor Priming: Compounds that prepare receptors for cannabinoid binding
    - Metabolic Enhancers: Compounds affecting cannabinoid metabolism
    - Synergistic: Compounds with additive/synergistic effects
    - Protective: Compounds that reduce side effects
    """
    __tablename__ = "adjuvants"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Identity
    name = Column(String(200), nullable=False, unique=True, index=True)
    common_names = Column(JSON)  # Alternative names
    smiles = Column(String(500))
    inchi_key = Column(String(100), index=True)
    
    # Classification
    category = Column(String(100), nullable=False, index=True)
    # Categories: "Receptor Priming", "Metabolic Enhancer", "Synergistic", 
    #             "Protective", "Bioavailability", "Terpene", "Other"
    subcategory = Column(String(100))
    compound_class = Column(String(100))  # amino_acid, mineral, vitamin, herb, etc.
    
    # Mechanism
    mechanism = Column(Text, nullable=False)
    target_receptors = Column(JSON)  # ["CB1", "GABA-A", "5-HT1A", etc.]
    pathway_effects = Column(JSON)  # Affected pathways
    
    # Dosing
    recommended_dose_mg = Column(Float, nullable=False)
    dose_range_min_mg = Column(Float)
    dose_range_max_mg = Column(Float)
    dose_form = Column(String(50))  # capsule, liquid, sublingual, etc.
    bioavailability_percent = Column(Float)
    
    # Timing
    timing_offset_minutes = Column(Integer, nullable=False, default=0)
    # Negative = before cannabinoid, Positive = after, 0 = concurrent
    timing_flexibility_minutes = Column(Integer, default=15)
    duration_hours = Column(Float)
    onset_minutes = Column(Integer)
    
    # Evidence
    evidence_tier = Column(Integer, nullable=False, default=3)
    # 1 = RCT/Meta-analysis, 2 = Clinical trial, 3 = In vivo, 4 = In vitro, 5 = Theoretical
    evidence_summary = Column(Text)
    pubmed_ids = Column(JSON)  # Supporting literature
    
    # Compatibility
    cannabinoid_synergies = Column(JSON)  # Which cannabinoids work best with
    contraindications = Column(JSON)  # When NOT to use
    drug_interactions = Column(JSON)  # Known interactions
    max_enhancement_percent = Column(Float)  # Expected effect enhancement
    
    # Safety
    is_otc = Column(Boolean, default=True)  # Over-the-counter available
    requires_prescription = Column(Boolean, default=False)
    pregnancy_category = Column(String(10))
    max_daily_dose_mg = Column(Float)
    side_effects = Column(JSON)
    
    # External IDs
    pubchem_cid = Column(String(50))
    drugbank_id = Column(String(50))
    
    # Status
    is_active = Column(Boolean, default=True)
    
    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    def __repr__(self):
        return f"<Adjuvant(name='{self.name}', category='{self.category}')>"


class PrimingProtocol(Base):
    """Optimized priming protocol combining adjuvants with cannabinoids.
    
    Generated by PrimingProtocolGenerator based on:
    - Target cannabinoid
    - Patient condition
    - Patient profile (allergies, medications, etc.)
    """
    __tablename__ = "priming_protocols"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Protocol Identity
    name = Column(String(200), nullable=False)
    protocol_code = Column(String(50), unique=True, index=True)
    version = Column(String(20), default="1.0")
    
    # Target
    target_cannabinoid_id = Column(Integer, ForeignKey("cannabinoids.id"))
    target_condition = Column(String(100), index=True)
    
    # Protocol Steps (ordered list of adjuvants + timing)
    steps = Column(JSON, nullable=False)
    # Example: [
    #   {"adjuvant_id": 1, "dose_mg": 200, "timing_minutes": -30, "notes": "Take with water"},
    #   {"adjuvant_id": 2, "dose_mg": 100, "timing_minutes": -15, "notes": "Sublingual"},
    #   {"cannabinoid": "primary", "timing_minutes": 0, "notes": "Standard dose"}
    # ]
    
    # Expected Outcomes
    expected_enhancement_percent = Column(Float)
    expected_onset_reduction_minutes = Column(Integer)
    expected_duration_extension_hours = Column(Float)
    
    # Confidence
    confidence_score = Column(Float)  # 0.0-1.0
    evidence_tier = Column(Integer)  # Lowest tier of included adjuvants
    
    # Contraindications
    contraindicated_conditions = Column(JSON)
    contraindicated_medications = Column(JSON)
    
    # Usage Stats
    times_generated = Column(Integer, default=0)
    patient_feedback_score = Column(Float)
    
    # Status
    is_validated = Column(Boolean, default=False)
    is_active = Column(Boolean, default=True)
    
    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, onupdate=func.now())
    
    def __repr__(self):
        return f"<PrimingProtocol(name='{self.name}', condition='{self.target_condition}')>"


class DrugInteraction(Base):
    """Drug interaction records for safety checking.
    
    Tracks interactions between:
    - Cannabinoids and medications
    - Adjuvants and medications
    - Cannabinoids and adjuvants
    """
    __tablename__ = "drug_interactions"
    
    id = Column(Integer, primary_key=True, index=True)
    
    # Interacting Compounds
    compound_a_type = Column(String(50), nullable=False)  # cannabinoid, adjuvant, medication
    compound_a_name = Column(String(200), nullable=False, index=True)
    compound_a_id = Column(Integer)  # FK to appropriate table
    
    compound_b_type = Column(String(50), nullable=False)
    compound_b_name = Column(String(200), nullable=False, index=True)
    compound_b_id = Column(Integer)
    
    # Interaction Details
    interaction_type = Column(String(100), nullable=False)
    # Types: "contraindicated", "major", "moderate", "minor", "synergistic"
    severity = Column(Integer, nullable=False)  # 1-5, 5 = most severe
    
    mechanism = Column(Text)
    clinical_effect = Column(Text, nullable=False)
    
    # Management
    management_recommendation = Column(Text)
    monitoring_required = Column(Boolean, default=False)
    monitoring_parameters = Column(JSON)
    
    # Evidence
    evidence_level = Column(String(50))  # established, theoretical, case_report
    pubmed_ids = Column(JSON)
    
    # Status
    is_active = Column(Boolean, default=True)
    last_reviewed = Column(DateTime)
    
    # Timestamps
    created_at = Column(DateTime, server_default=func.now())
    
    def __repr__(self):
        return f"<DrugInteraction({self.compound_a_name} + {self.compound_b_name}: {self.interaction_type})>"
